# Generated by Django 5.1.6 on 2025-02-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_projetolei_title_alter_projetolei_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetolei',
            name='legislature',
            field=models.CharField(max_length=10),
        ),
    ]
