# Generated by Django 5.1.6 on 2025-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_projetolei_legislature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projetolei',
            name='phases',
            field=models.ManyToManyField(blank=True, related_name='projetos_lei', to='backend.phase'),
        ),
    ]
