# Generated by Django 5.1.6 on 2025-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_phase_projetolei_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='phases',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='projetos_lei', to='backend.phase'),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='title',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='type',
            field=models.CharField(db_index=True),
        ),
    ]
