# Generated by Django 5.1.6 on 2025-02-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_phase_name_alter_projetolei_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetolei',
            name='phase',
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='title',
            field=models.TextField(db_index=True),
        ),
    ]
