# Generated by Django 5.1.6 on 2025-02-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_projetolei_phase_alter_projetolei_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('author_type', models.CharField(choices=[('Deputado', 'Deputado'), ('Grupo', 'Grupo'), ('Outro', 'Outro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projetolei',
            name='author',
        ),
        migrations.AddField(
            model_name='projetolei',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='publication_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='related_initiatives',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='backend.projetolei'),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='projetos_lei', to='backend.attachment'),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='authors',
            field=models.ManyToManyField(related_name='projetos_lei', to='backend.author'),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='legislature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_lei', to='backend.legislature'),
        ),
        migrations.AddField(
            model_name='projetolei',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='projetos_lei', to='backend.vote'),
        ),
    ]
