# Generated by Django 5.1.6 on 2025-02-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_attachment_author_legislature_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
