# Generated by Django 5.1.6 on 2025-02-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_vote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetolei',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
