# Generated by Django 4.2.19 on 2025-02-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='votes',
            field=models.JSONField(default=dict),
        ),
    ]
