# Generated by Django 4.2.19 on 2025-02-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_vote_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
