# Generated by Django 4.2.19 on 2025-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_commission_debate_attachment_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetolei',
            name='external_id',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
    ]
