# Generated by Django 4.2.19 on 2025-03-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_projetolei_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetolei',
            name='link',
        ),
        migrations.AlterField(
            model_name='approvedtext',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='commissiondocument',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='publication_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='text_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
