# Generated by Django 4.2.19 on 2025-03-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_projetolei_link_alter_approvedtext_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetolei',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
