version: '3.8'

services:
  django:
    build:
      context: ./django-app
    volumes:
      - ./django-app:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - app-network

  nextjs:
    build:
      context: ./nextjs-app
    volumes:
      - ./nextjs-app:/app
    ports:
      - "3000:3000"
    depends_on:
      - django
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
