version: '3.8'

services:
  web:
    build: .
    container_name: django_api
    restart: always
    env_file: .env
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_API_KEY: ${SUPABASE_API_KEY}
      SUPABASE_HOST: ${SUPABASE_HOST}
