version: '3.8'

services:
  web:
    build: .
    container_name: django_api
    restart: always
    env_file: .env
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgres" # Make sure to update with the correct connection string
    networks:
      - postgresql_app_network  # Ensure this matches the actual network name

networks:
  postgresql_app_network:
    external: true  # Use an existing network
