version: '3.8'

services:
  web:
    build: .
    container_name: django_api
    restart: always
    env_file: .env
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}  # This should contain the correct connection string for PostgreSQL
    depends_on:
      - db

  # PostgreSQL container is no longer needed since it's running externally.
  db:
    external: true
    name: existing_postgres_container_name  # Replace with your actual PostgreSQL container name

networks:
  app_network:
    external: true  # Use existing network if needed (if both containers are on the same network)
